"""
Exporters for the generated briefs.

- Markdown: clean, copy-pasteable for GitHub READMEs
- HTML:     self-contained, prints beautifully
- JSON:     machine-readable for integrations
- Shareable: an SVG card designed to win screenshots
"""
from __future__ import annotations

import json
from datetime import datetime
from typing import Optional

from models import Project


# ── Markdown ─────────────────────────────────────────────────────────────
def to_markdown(project: Project) -> str:
    """Render a project as a GitHub-ready Markdown brief."""
    lines = [
        f"# {project.name}",
        "",
        f"> {project.tagline}",
        "",
        "## Problem",
        "",
        project.problem,
        "",
        "## Solution",
        "",
        project.solution,
        "",
        "## Features",
        "",
    ]
    for f in project.features:
        lines.append(f"- {f}")
    lines += ["", "## Tech stack", ""]
    for s in project.stack:
        lines.append(f"- {s}")
    if project.marketing:
        lines += ["", "## Marketing", "", project.marketing, ""]
    lines += [
        "",
        "---",
        f"_Generated on {project.created_at.strftime('%Y-%m-%d %H:%M')} "
        f"with [Devpost Companion](https://github.com/yourname/devpost-companion)._",
    ]
    return "\n".join(lines)


# ── HTML ─────────────────────────────────────────────────────────────────
HTML_TEMPLATE = """<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8" />
<title>{name} — Devpost Companion</title>
<meta name="viewport" content="width=device-width, initial-scale=1" />
<style>
  body {{
    font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif;
    background: linear-gradient(135deg, #0f172a 0%, #1e293b 100%);
    color: #e2e8f0; max-width: 760px; margin: 0 auto; padding: 48px 24px;
  }}
  h1 {{ font-size: 2.5rem; margin: 0 0 8px; color: #f8fafc; }}
  .tagline {{ font-size: 1.2rem; color: #94a3b8; border-left: 4px solid #6366f1;
              padding-left: 12px; margin: 16px 0 32px; }}
  h2 {{ color: #a5b4fc; margin-top: 32px; }}
  ul {{ padding-left: 20px; }}
  li {{ margin: 6px 0; }}
  .footer {{ margin-top: 48px; font-size: 0.85rem; color: #64748b; }}
  code {{ background: #1e293b; padding: 2px 6px; border-radius: 4px; }}
</style>
</head>
<body>
  <h1>{name}</h1>
  <div class="tagline">{tagline}</div>
  <h2>Problem</h2><p>{problem}</p>
  <h2>Solution</h2><p>{solution}</p>
  <h2>Features</h2><ul>{features}</ul>
  <h2>Tech stack</h2><ul>{stack}</ul>
  {marketing_block}
  <div class="footer">Generated by Devpost Companion on {date}.</div>
</body>
</html>"""


def _html_escape(text: str) -> str:
    return (text.replace("&", "&amp;")
                .replace("<", "&lt;")
                .replace(">", "&gt;")
                .replace("\n", "<br/>"))


def to_html(project: Project) -> str:
    """Render a self-contained HTML brief."""
    features = "".join(f"<li>{_html_escape(f)}</li>" for f in project.features)
    stack = "".join(f"<li>{_html_escape(s)}</li>" for s in project.stack)
    marketing_block = (
        f"<h2>Marketing</h2><p>{_html_escape(project.marketing)}</p>"
        if project.marketing else ""
    )
    return HTML_TEMPLATE.format(
        name=_html_escape(project.name or "Untitled"),
        tagline=_html_escape(project.tagline or ""),
        problem=_html_escape(project.problem or ""),
        solution=_html_escape(project.solution or ""),
        features=features,
        stack=stack,
        marketing_block=marketing_block,
        date=project.created_at.strftime("%Y-%m-%d %H:%M") if project.created_at else "",
    )


# ── JSON ─────────────────────────────────────────────────────────────────
def to_json(project: Project) -> str:
    """Render the project as a JSON string (pretty-printed)."""
    return json.dumps(project.to_dict(), indent=2, ensure_ascii=False)


# ── Shareable card (SVG) ────────────────────────────────────────────────
def to_shareable_svg(project: Project) -> str:
    """Render a 1200x630 shareable card (Twitter / OG dimensions)."""
    name = (project.name or "Untitled")[:60]
    tagline = (project.tagline or "")[:160]
    features = project.features[:3] if project.features else ["AI", "Fast", "Beautiful"]
    feature_text = "  •  ".join(features)

    return f"""<svg xmlns="http://www.w3.org/2000/svg" width="1200" height="630" viewBox="0 0 1200 630">
  <defs>
    <linearGradient id="bg" x1="0" y1="0" x2="1" y2="1">
      <stop offset="0%" stop-color="#0f172a"/>
      <stop offset="50%" stop-color="#312e81"/>
      <stop offset="100%" stop-color="#7c3aed"/>
    </linearGradient>
    <radialGradient id="glow" cx="0.8" cy="0.2" r="0.6">
      <stop offset="0%" stop-color="#fbbf24" stop-opacity="0.4"/>
      <stop offset="100%" stop-color="#fbbf24" stop-opacity="0"/>
    </radialGradient>
  </defs>
  <rect width="1200" height="630" fill="url(#bg)"/>
  <rect width="1200" height="630" fill="url(#glow)"/>
  <g transform="translate(80, 80)">
    <text x="0" y="0" font-family="-apple-system, sans-serif" font-size="28"
          font-weight="600" fill="#a5b4fc" letter-spacing="2">DEVPOST COMPANION</text>
    <text x="0" y="100" font-family="-apple-system, sans-serif" font-size="86"
          font-weight="800" fill="#ffffff">{_xml_escape(name)}</text>
    <text x="0" y="170" font-family="-apple-system, sans-serif" font-size="32"
          font-weight="400" fill="#cbd5e1">{_xml_escape(tagline)}</text>
    <line x1="0" y1="220" x2="200" y2="220" stroke="#fbbf24" stroke-width="4"/>
    <text x="0" y="280" font-family="-apple-system, sans-serif" font-size="24"
          fill="#e2e8f0">{_xml_escape(feature_text)}</text>
    <text x="0" y="500" font-family="-apple-system, sans-serif" font-size="22"
          fill="#94a3b8">From idea to submission-ready in 30 seconds.</text>
  </g>
  <g transform="translate(1040, 540)">
    <circle r="40" fill="#fbbf24"/>
    <text x="0" y="8" text-anchor="middle" font-family="sans-serif" font-size="40">⚡</text>
  </g>
</svg>"""


def _xml_escape(text: str) -> str:
    return (text.replace("&", "&amp;")
                .replace("<", "&lt;")
                .replace(">", "&gt;")
                .replace('"', "&quot;"))